### ISSUE TITLE
ESLINT error (no-throw-literal) para task 'Repositório Duplicado'

### ISSUE THREAD

**Issue by lukemorales** [Rocketseat/bootcamp-gostack-desafio-05#1]
> ### Repositório duplicado
> Antes de fazer a chamada à API na função handleSubmit faça uma verificação para ver se o repositório não está duplicado, ou seja, se ele ainda não existe no estado de repositories.
> Caso exista, dispare um erro, e com isso o código cairá no catch do try/catch criado na funcionalidade anterior.
> throw 'Repositório duplicado';
---

O ESLint acusa o erro [(no-throw-literal)](https://eslint.org/docs/rules/no-throw-literal) como não sendo uma boa prática enviar uma string direta em erros, mas sim dando preferência para enviar o objeto `Error` ou alguma função que tenham a possibilidade de ser um objeto `Error`.

A solução mais simples para esse caso seria:
```javascript
throw new Error('Repositório duplicado');
```

**Comment by diego3g** [comment]
Fala @lukemorales, podes enviar uma PR com essa sugestão?
