### ISSUE TITLE
Repositório duplicado - Vue

### ISSUE THREAD

**Issue by ThiagoLeite06** [Rocketseat/bootcamp-gostack-desafio-05#12]
Estive praticando o desafio proposto e como de costume sempre testava três repositórios: rocketseat/unform, facebook/react e vue/vue.

Sempre que coloco vue/vue ele passa.

Notei que ele leva em considerção letras maiusculas, pois VUE/VUE não passa. E se o nome for o mesmo mas escrito de um forma diferente (caixa alta ou baixa) ele acaba passando.

Não sei se uma issue seria o correto a fazer, mas também preciso me familiarizar com o GitHub ;p 

Vou tomar como um desafio extra uma solução.

**Comment by sajermann** [comment]
Passei por esse problema também, resolvi usando o bom e velho toLowerCase()
